version: '3'

services:
  mediathekview:
    build: .
    container_name: mediathekview
    ports:
      - "5800:5800"
    volumes:
      - "$HOME/.mediathek3:/config:rw"
      - "$HOME/MediathekView:/output:rw"
    environment:
       - "UID=1000"
       - "GID=1000"
